sudo: required

language: python

os:
  - linux

env:
  # code style
  - TASK=lint
  # run examples/
  - TASK=example_test


python:
  - 2.7
  - 3.5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-dev
      - libopencv-dev
      - gcc-4.8
      - g++-4.8
      - python-numpy
      - python-nose
      - python3-numpy
      - python3-dev
      - python3-nose
      - graphviz
      - libatlas-base-dev
      - libblas-dev
      - libatlas3gf-base
      - gfortran

before_install:
  - git clone --recursive https://github.com/dmlc/mxnet.git
  # set up travis path & nnvm settings
  - source mxnet/dmlc-core/scripts/travis/travis_setup_env.sh
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/mxnet/python
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=256m -XX:-UseGCOverheadLimit -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

install:
  - sudo pip install --upgrade pip
  - pip install cpplint pylint PyYAML h5py scipy Pillow
  - pip3 install cpplint pylint PyYAML h5py scipy Pillow
  # Temporary fix libdc1394 error
  - sudo ln /dev/null /dev/raw1394
  - cd mxnet
  - source tests/travis/setup.sh
  - cd ..
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

script:
  - travis/run_test.sh

deploy:
  provider: pypi
  user: hotpxl
  on:
    tags: true
  distributions: sdist bdist_wheel
  docs_dir: docs/pypi
  password:
    secure: ZVPpLvHzH16dJfuWR3Iqtulv6gXilw1//SzLVYzg8LoqG108qxaE99GeC1rPcsCAJCAfsoqNbZtd/VvtnLoaTTJojbTocpmC1o7rHmsXkDWZ/vcruRZHSJCZIKbjkjr1PxNHD1y2LSJMib1tyrGGi+1wiljCKkb4OKjRgvIfYHjmsDatR7FfMSuw0SNhIPflonKeAKLcKhRdEYqNfyv9auOsd1Mhl+TxqLZqgFq6Zw1XyTcq/b2x8TX3K0U/M7v9UA224I78xqAFzRoqwtgG3sDxmeGCTENmeQ46+ty/FNH0X9IjkPMIT6vHhAzG14Hi4rhaDsLTU3ICWsGYA25+uKvVgxRXrKG2O+x7VQe3+D+u5+iu2E7UH57u+mX25opWl7fQ2begULUWtsqckxZcdPm5i4HV26xIf7yUFm9CvJYotLveirUdb1hP+dGkcZJZps1sDNOQvKRK+2TVLXcJQ6xOML5r+d82nIC6efVRFUKXYY7VZLutVrM7krJ69s+t5K/3NN8aMJ0ap9Rsau4jg3ws3Fuo5wDnqAfpl/wiJ4X4yK9H62dkiOXwnvxKnp4iRvU1Ks9P8ydYVLVOERaMqMEIeuFuP3tdH01anwrpvjQdQjak7K9dfFBWn++vS/w6UVTMT0N5l4UJuSBCiPLd4NLoHX/p50EOPFJQoe8LVRc=
